name: cryptopals
version: 0.1.0.0
github: "Per48edjes/cryptopals"
license: BSD3
author: "Ravi Dayabhai"
maintainer: "r.i.dayabhai@gmail.com"
copyright: "2023 Ravi Dayabhai"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Per48edjes/cryptopals#readme>

dependencies:
  - base >= 4.7 && < 5
  - base16-bytestring
  - base64-bytestring
  - bytestring
  - cereal
  - containers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  exposed-modules:
    - Lib
  source-dirs: src
  default-extensions:
    - ImportQualifiedPost

_exe-defs: &exe-defaults
  source-dirs: app
  default-extensions:
    - ImportQualifiedPost
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  dependencies:
    - cryptopals

executables:
  challenge-set-1:
    <<: *exe-defaults
    main: ChallengeSet1.hs
    ghc-options:
      - -main-is ChallengeSet1
  challenge-set-2:
    <<: *exe-defaults
    main: ChallengeSet2.hs
    ghc-options:
      - -main-is ChallengeSet2

tests:
  cryptopals-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cryptopals
